# Numpy Lib guide on how to use it

In [2]:
import numpy as np

## Basics

In [3]:
# dtype param used to store the info in less space
a = np.array([1, 2, 3, 4], dtype='int16')
print(a)

[1 2 3 4]


In [4]:
b = np.array([[1, 9.06, 32, 5], [1.02, 3, 4.0, 45]])
print(b)
# !!! Arrays must be homogeneous -> same no of elemes per row

[[ 1.    9.06 32.    5.  ]
 [ 1.02  3.    4.   45.  ]]


In [5]:
# Getting the Dimensions
a.ndim 

1

In [6]:
# Getting the Shape
# if 1D -> (no_elem, )
# if kD -> (no_rows, no_elems)
print(f"1D array A: {a.shape}\n2D array B: {b.shape}")

1D array A: (4,)
2D array B: (2, 4)


In [7]:
# Getting the Type
# Default type for int is int64
# to change this specify the type when creating it with dtype=''
a.dtype

dtype('int16')

In [ ]:
# Getting the size of the data(int bytes)
a.itemsize # returns 2 <=> int16 -> 16 bits -> 2 bytes

2

In [10]:
# Getting the total size(int bytes)
a.nbytes

8

## Accessing/Changing specific elements, rows, columns...

In [14]:
a = np.array([[1, 2, 6, 5, 4, 2, 3], [5, 3, 4, 2, 1, 4, 5]], dtype='int16')
print(a.shape)

(2, 7)


In [15]:
# Get a specific elem [r, c]
a[1, 5]

np.int16(4)

In [16]:
# Get a row
a[0, :]

array([1, 2, 6, 5, 4, 2, 3], dtype=int16)

In [17]:
# Get a column
a[:, 2]

array([6, 4], dtype=int16)

In [19]:
# Getting elems based on a range [start:end:step]
a[0, 1:-1:2]

array([2, 5, 2], dtype=int16)

In [20]:
# Changing the element
a[1, 5] = 10

# Changing entire rows/columns
a[:, 2] = 20

print(a)

[[ 1  2 20  5  4  2  3]
 [ 5  3 20  2  1 10  5]]


### Initializing different Types of Arrays


In [21]:
# NULL MATRIX
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# UNIT MATRIX
np.ones((2, 3, 3), dtype="int32")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [ ]:
# CREATING A MATRIX WITH A NON BOOLEAN VALUE
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [26]:
# CREATING A MATRIX USING A TEMPLATE(2 WAYS)
# first way
print(np.full(a.shape, 100))
#second way
print(np.full_like(a, 200))

[[100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]]
[[200 200 200 200 200 200 200]
 [200 200 200 200 200 200 200]]


In [30]:
#Random decimal Matrix
print(np.random.rand(4, 2, 2))
#To use a Shape in place of the coord
print("_____________________________")
print(np.random.random_sample(a.shape))

[[[0.64201804 0.10124677]
  [0.03659738 0.15449666]]

 [[0.84332762 0.02989339]
  [0.35921521 0.57467428]]

 [[0.50585234 0.03229818]
  [0.66517415 0.87708214]]

 [[0.36842424 0.13244084]
  [0.24565471 0.2575359 ]]]
_____________________________
[[0.91809803 0.22849488 0.70525651 0.57627598 0.34356863 0.60856919
  0.34582951]
 [0.55958169 0.17868083 0.8742036  0.97602638 0.29354086 0.56555431
  0.9226297 ]]


In [35]:
#Generating integer randoms
np.random.randint(7, size=(3, 3))

array([[0, 3, 3],
       [5, 3, 2],
       [4, 5, 5]], dtype=int32)

In [36]:
# IDENTITY MATRIX
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeating the array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
#axis here are related to the dimensions of the repeated vector
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [45]:
# Beispiel
# Matrix 1 1 1 1 1
#        1 0 0 0 1
#        1 0 9 0 1
#        1 0 0 0 1
#        1 1 1 1 1
mat = np.ones((5, 5))
mat[1:4, 1:-1] = 0
mat[2, 2] = 9
print(mat)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Careful with copying arrays

In [ ]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
# the element change in b will triger a change in a
# the '=' is a assingment of the address
print(a)

print('________________________')
# Use .copy() for a deep copy
c = a.copy()
c[0] = 5
print(a)

[100   2   3]
________________________
[100   2   3]


# Mathematics in Numpy


In [54]:
# Object wise operations
print(a + 2)
print(a / 2)
print(a * 2)
print(a + c)
print(np.cos(a))

[102   4   5]
[50.   1.   1.5]
[200   4   6]
[105   4   6]
[ 0.86231887 -0.41614684 -0.9899925 ]


### Liniar Algebra


In [ ]:
# find the determinant of a matrix
# to use the liniar algebra functions np.linalg.*
I = np.identity(3)
np.linalg.det(I)

np.float64(1.0)

#### Statistics


In [6]:
# Axis specifies the direction of the operations
# axis=0 => direction vertically
# axis=1 => direction horizontally
# axis=2 => for 3D arrays height
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(f"{np.min(stats, axis=1)} min value based on a axis(axis=1) computation")
print(f"{np.min(stats)} minimal value of the all elements")

print(f"{np.sum(stats, axis=0)} sums of the columns of a 2D array")

[1 4] min value based on a axis(axis=1) computation
1 minimal value of the all elements
[5 7 9] sums of the columns of a 2D array


#### Reorganizing Arrays

In [7]:
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(f"{before} - array before being modified")

after = before.reshape((2, 2, 2))
print(f"{after} - array after being reshaped in a (2, 2, 2)")

[[1 2 3 4]
 [5 6 7 8]] - array before being modified
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] - array after being reshaped in a (2, 2, 2)


In [11]:
# Vertically stacking arrays
v1 = np.array([1, 2, 3, 4])
v2 = np.array([6, 7, 8, 9])

print(np.stack([v1, v2, v2, v1]))

print()
# Horizontally stacking arrays
print(np.hstack([v1, v2]))

[[1 2 3 4]
 [6 7 8 9]
 [6 7 8 9]
 [1 2 3 4]]

[1 2 3 4 6 7 8 9]


#### Miscellaneous

##### Load data from File


In [ ]:
# Automatically cast the data into float type
file_data = np.genfromtxt('file.txt', delimiter=',')
# Change the type of the values
file_data_int = file_data.astype('int32')

file_data_int


array([[ 1,  2,  3, 54, 12, 43, 12, 98, 47, 97, 10, 18],
       [ 1, 27, 31,  5,  2, 23,  8, 91, 45, 17, 13, 19],
       [ 1,  0, 33, 54, 10,  3, 11, 93, 40, 87, 14, 13],
       [ 1,  9, 23, 54, 11,  4, 13, 90, 17, 96, 15, 10]], dtype=int32)

##### Boolean Masking and Advanced Indexing

In [24]:
# I want where in file_data the value is bigger then 50
# returns a matrix of boolean 
print(file_data_int > 50)

# indexing based on the boolean value
# retunrs only the values that are > 50
print() 
print(file_data_int[file_data_int > 50])

# indexing with a list
print()
print(file_data_int[[1, 3]])

# using helper functions
print()
# what columns have at least one value bigger then 50 on the column
print(np.any(file_data_int > 50, axis=0))

# what rows have all the values bigger then 50
print()
print(np.all(file_data_int > 50, axis=1))

# logical operations 
print()
print(((file_data_int > 50) & (file_data_int < 150)))

[[False False False  True False False False  True False  True False False]
 [False False False False False False False  True False False False False]
 [False False False  True False False False  True False  True False False]
 [False False False  True False False False  True False  True False False]]

[54 98 97 91 54 93 87 54 90 96]

[[ 1 27 31  5  2 23  8 91 45 17 13 19]
 [ 1  9 23 54 11  4 13 90 17 96 15 10]]

[False False False  True False False False  True False  True False False]

[False False False False]

[[False False False  True False False False  True False  True False False]
 [False False False False False False False  True False False False False]
 [False False False  True False False False  True False  True False False]
 [False False False  True False False False  True False  True False False]]


In [31]:
arr = np.array([[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8], [-5, -6, -7, -8]])
arr[[0, -1, -2], :]

array([[ 1,  2,  3,  4],
       [-5, -6, -7, -8],
       [ 5,  6,  7,  8]])